(define app (lambda args (if #f #f)))
(define app.mgr (lambda args (if #f #f)))
(define app.mgr.op (lambda args (if #f #f)))
(app.mgr.op (list "type" "create" "pr_id" "pr_1" "draft" #t))
(app.mgr.op (list "type" "create" "pr_id" "pr_2"))
