def record_value(*_args: object, **_kwargs: object) -> object: ...
def flush_buffer(*_args: object, **_kwargs: object) -> object: ...
def emit(*_args: object, **_kwargs: object) -> object: ...
emit(record_value(value=42))
flush_buffer(count=3)
