class _ThrottlerType:
    def check(self, *_args: object, **_kwargs: object) -> object: ...
throttler = _ThrottlerType()
def emit(*_args: object, **_kwargs: object) -> object: ...
emit(throttler.check("user_1", 1000.0))
emit(throttler.check("user_2", 2000.5))
