module Check where


import Data.Argonaut.Core (Json, jsonNull)
import Data.Argonaut.Parser (jsonParser)
import Data.Either (fromRight)


my_data :: Json
my_data = fromRight jsonNull (jsonParser "{\"long_str\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", \"quoted\": \"a\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"ba\\\"b\", \"wide\": \"中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中中\"}")
