def process(*_args: object, **_kwargs: object) -> object: ...
def emit(*_args: object, **_kwargs: object) -> object: ...
emit(process(value="hello"), {"a": 1, "b": 2})
emit(process(value=42), {"c": 3, "d": 4})
