#!/usr/bin/env python3
"""Concatenate C++ fixtures into one TU for clang-tidy.

Each fixture is a tiny file whose parse cost is dominated by re-parsing
the same standard headers. Running clang-tidy once on a single blob
amortizes STL parsing and `clang-analyzer-*` initialization across all
fixtures instead of paying it per file.
"""

from __future__ import annotations

import pathlib
import re
import sys

_INCLUDE_RE = re.compile(r'^\s*#\s*include\s*[<"][^>"]+[>"]')


def _split_fixture(text: str) -> tuple[list[str], list[str], int]:
    """Return (includes, body_lines, body_start_lineno) for a fixture."""
    lines = text.splitlines()
    includes: list[str] = []
    body_start = 0
    for i, line in enumerate(lines):
        if _INCLUDE_RE.match(line):
            includes.append(line.strip())
            body_start = i + 1
        elif line.strip() == "":
            body_start = i + 1
        else:
            break
    return includes, lines[body_start:], body_start + 1


def _render(*, root: pathlib.Path) -> str:
    """Render the concatenated blob for all C++ fixtures under
    ``root``.
    """
    fixtures = sorted(root.rglob("*.cpp"))
    all_includes: set[str] = set()
    chunks: list[tuple[int, pathlib.Path, list[str], int]] = []
    for idx, path in enumerate(fixtures):
        includes, body, body_lineno = _split_fixture(text=path.read_text())
        all_includes.update(includes)
        chunks.append((idx, path, body, body_lineno))
    parts: list[str] = [
        "// Auto-generated by generate-cpp-tidy-blob.py; do not edit.",
    ]
    parts.extend(sorted(all_includes))
    for idx, path, body, body_lineno in chunks:
        parts.append(f"namespace fixture_{idx} {{")
        parts.append(f'#line {body_lineno} "{path}"')
        parts.extend(body)
        parts.append(f"}}  // namespace fixture_{idx}")
    return "\n".join(parts) + "\n"


def main(argv: list[str]) -> int:
    """Write the concatenated blob from fixtures under argv[1] to
    argv[2].
    """
    root = pathlib.Path(argv[1])
    out = pathlib.Path(argv[2])
    out.write_text(data=_render(root=root))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
