#include <stdbool.h>
#include <stddef.h>
typedef struct CVal CVal;
typedef struct CKV CKV;
struct CVal {
    union {
        _Bool b;
        long long i;
        unsigned long long u;
        double f;
        const char *s;
        const CVal *a;
        const CKV *m;
    };
};
struct CKV { const char *k; CVal v; };
int main(void) {
CVal my_data = ((CVal){.a = (CVal[]){
    ((CVal){.i = 0}),
    ((CVal){.i = 1}),
    ((CVal){.i = 2}),
    ((CVal){.i = 3}),
    ((CVal){.i = 4}),
    ((CVal){.i = 5}),
    ((CVal){.i = 6}),
    ((CVal){.i = 7}),
    ((CVal){.i = 8}),
    ((CVal){.i = 9}),
    ((CVal){.i = 10}),
    ((CVal){.i = 11}),
    ((CVal){.i = 12}),
    ((CVal){.i = 13}),
    ((CVal){.i = 14}),
    ((CVal){.i = 15}),
    ((CVal){.i = 16}),
    ((CVal){.i = 17}),
    ((CVal){.i = 18}),
    ((CVal){.i = 19}),
    ((CVal){.i = 20}),
    ((CVal){.i = 21}),
    ((CVal){.i = 22}),
    ((CVal){.i = 23}),
    ((CVal){.i = 24}),
    ((CVal){.i = 25}),
    ((CVal){.i = 26}),
    ((CVal){.i = 27}),
    ((CVal){.i = 28}),
    ((CVal){.i = 29}),
    ((CVal){.i = 30}),
    ((CVal){.i = 31}),
    ((CVal){.i = 32}),
    ((CVal){.i = 33}),
    ((CVal){.i = 34}),
    ((CVal){.i = 35}),
    ((CVal){.i = 36}),
    ((CVal){.i = 37}),
    ((CVal){.i = 38}),
    ((CVal){.i = 39}),
    ((CVal){.i = 40}),
    ((CVal){.i = 41}),
    ((CVal){.i = 42}),
    ((CVal){.i = 43}),
    ((CVal){.i = 44}),
    ((CVal){.i = 45}),
    ((CVal){.i = 46}),
    ((CVal){.i = 47}),
    ((CVal){.i = 48}),
    ((CVal){.i = 49}),
    ((CVal){.i = 50}),
    ((CVal){.i = 51}),
    ((CVal){.i = 52}),
    ((CVal){.i = 53}),
    ((CVal){.i = 54}),
    ((CVal){.i = 55}),
    ((CVal){.i = 56}),
    ((CVal){.i = 57}),
    ((CVal){.i = 58}),
    ((CVal){.i = 59}),
    ((CVal){.i = 60}),
    ((CVal){.i = 61}),
    ((CVal){.i = 62}),
    ((CVal){.i = 63}),
    ((CVal){.i = 64}),
    ((CVal){.i = 65}),
    ((CVal){.i = 66}),
    ((CVal){.i = 67}),
    ((CVal){.i = 68}),
    ((CVal){.i = 69}),
    ((CVal){.i = 70}),
    ((CVal){.i = 71}),
    ((CVal){.i = 72}),
    ((CVal){.i = 73}),
    ((CVal){.i = 74}),
    ((CVal){.i = 75}),
    ((CVal){.i = 76}),
    ((CVal){.i = 77}),
    ((CVal){.i = 78}),
    ((CVal){.i = 79}),
    ((CVal){.i = 80}),
    ((CVal){.i = 81}),
    ((CVal){.i = 82}),
    ((CVal){.i = 83}),
    ((CVal){.i = 84}),
    ((CVal){.i = 85}),
    ((CVal){.i = 86}),
    ((CVal){.i = 87}),
    ((CVal){.i = 88}),
    ((CVal){.i = 89}),
    ((CVal){.i = 90}),
    ((CVal){.i = 91}),
    ((CVal){.i = 92}),
    ((CVal){.i = 93}),
    ((CVal){.i = 94}),
    ((CVal){.i = 95}),
    ((CVal){.i = 96}),
    ((CVal){.i = 97}),
    ((CVal){.i = 98}),
    ((CVal){.i = 99}),
    ((CVal){.i = 100}),
    ((CVal){.i = 101}),
    ((CVal){.i = 102}),
    ((CVal){.i = 103}),
    ((CVal){.i = 104}),
    ((CVal){.i = 105}),
    ((CVal){.i = 106}),
    ((CVal){.i = 107}),
    ((CVal){.i = 108}),
    ((CVal){.i = 109}),
    ((CVal){.i = 110}),
    ((CVal){.i = 111}),
    ((CVal){.i = 112}),
    ((CVal){.i = 113}),
    ((CVal){.i = 114}),
    ((CVal){.i = 115}),
    ((CVal){.i = 116}),
    ((CVal){.i = 117}),
    ((CVal){.i = 118}),
    ((CVal){.i = 119}),
}});
    (void)my_data;
    return 0;
}
