#include <cjson/cJSON.h>
int main(void) {
cJSON *_n0 = cJSON_CreateArray();
cJSON *_n1 = cJSON_CreateNumber((double)0);
cJSON_AddItemToArray(_n0, _n1);
cJSON *_n2 = cJSON_CreateNumber((double)1);
cJSON_AddItemToArray(_n0, _n2);
cJSON *_n3 = cJSON_CreateNumber((double)2);
cJSON_AddItemToArray(_n0, _n3);
cJSON *_n4 = cJSON_CreateNumber((double)3);
cJSON_AddItemToArray(_n0, _n4);
cJSON *_n5 = cJSON_CreateNumber((double)4);
cJSON_AddItemToArray(_n0, _n5);
cJSON *_n6 = cJSON_CreateNumber((double)5);
cJSON_AddItemToArray(_n0, _n6);
cJSON *_n7 = cJSON_CreateNumber((double)6);
cJSON_AddItemToArray(_n0, _n7);
cJSON *_n8 = cJSON_CreateNumber((double)7);
cJSON_AddItemToArray(_n0, _n8);
cJSON *_n9 = cJSON_CreateNumber((double)8);
cJSON_AddItemToArray(_n0, _n9);
cJSON *_n10 = cJSON_CreateNumber((double)9);
cJSON_AddItemToArray(_n0, _n10);
cJSON *_n11 = cJSON_CreateNumber((double)10);
cJSON_AddItemToArray(_n0, _n11);
cJSON *_n12 = cJSON_CreateNumber((double)11);
cJSON_AddItemToArray(_n0, _n12);
cJSON *_n13 = cJSON_CreateNumber((double)12);
cJSON_AddItemToArray(_n0, _n13);
cJSON *_n14 = cJSON_CreateNumber((double)13);
cJSON_AddItemToArray(_n0, _n14);
cJSON *_n15 = cJSON_CreateNumber((double)14);
cJSON_AddItemToArray(_n0, _n15);
cJSON *_n16 = cJSON_CreateNumber((double)15);
cJSON_AddItemToArray(_n0, _n16);
cJSON *_n17 = cJSON_CreateNumber((double)16);
cJSON_AddItemToArray(_n0, _n17);
cJSON *_n18 = cJSON_CreateNumber((double)17);
cJSON_AddItemToArray(_n0, _n18);
cJSON *_n19 = cJSON_CreateNumber((double)18);
cJSON_AddItemToArray(_n0, _n19);
cJSON *_n20 = cJSON_CreateNumber((double)19);
cJSON_AddItemToArray(_n0, _n20);
cJSON *_n21 = cJSON_CreateNumber((double)20);
cJSON_AddItemToArray(_n0, _n21);
cJSON *_n22 = cJSON_CreateNumber((double)21);
cJSON_AddItemToArray(_n0, _n22);
cJSON *_n23 = cJSON_CreateNumber((double)22);
cJSON_AddItemToArray(_n0, _n23);
cJSON *_n24 = cJSON_CreateNumber((double)23);
cJSON_AddItemToArray(_n0, _n24);
cJSON *_n25 = cJSON_CreateNumber((double)24);
cJSON_AddItemToArray(_n0, _n25);
cJSON *_n26 = cJSON_CreateNumber((double)25);
cJSON_AddItemToArray(_n0, _n26);
cJSON *_n27 = cJSON_CreateNumber((double)26);
cJSON_AddItemToArray(_n0, _n27);
cJSON *_n28 = cJSON_CreateNumber((double)27);
cJSON_AddItemToArray(_n0, _n28);
cJSON *_n29 = cJSON_CreateNumber((double)28);
cJSON_AddItemToArray(_n0, _n29);
cJSON *_n30 = cJSON_CreateNumber((double)29);
cJSON_AddItemToArray(_n0, _n30);
cJSON *_n31 = cJSON_CreateNumber((double)30);
cJSON_AddItemToArray(_n0, _n31);
cJSON *_n32 = cJSON_CreateNumber((double)31);
cJSON_AddItemToArray(_n0, _n32);
cJSON *_n33 = cJSON_CreateNumber((double)32);
cJSON_AddItemToArray(_n0, _n33);
cJSON *_n34 = cJSON_CreateNumber((double)33);
cJSON_AddItemToArray(_n0, _n34);
cJSON *_n35 = cJSON_CreateNumber((double)34);
cJSON_AddItemToArray(_n0, _n35);
cJSON *_n36 = cJSON_CreateNumber((double)35);
cJSON_AddItemToArray(_n0, _n36);
cJSON *_n37 = cJSON_CreateNumber((double)36);
cJSON_AddItemToArray(_n0, _n37);
cJSON *_n38 = cJSON_CreateNumber((double)37);
cJSON_AddItemToArray(_n0, _n38);
cJSON *_n39 = cJSON_CreateNumber((double)38);
cJSON_AddItemToArray(_n0, _n39);
cJSON *_n40 = cJSON_CreateNumber((double)39);
cJSON_AddItemToArray(_n0, _n40);
cJSON *_n41 = cJSON_CreateNumber((double)40);
cJSON_AddItemToArray(_n0, _n41);
cJSON *_n42 = cJSON_CreateNumber((double)41);
cJSON_AddItemToArray(_n0, _n42);
cJSON *_n43 = cJSON_CreateNumber((double)42);
cJSON_AddItemToArray(_n0, _n43);
cJSON *_n44 = cJSON_CreateNumber((double)43);
cJSON_AddItemToArray(_n0, _n44);
cJSON *_n45 = cJSON_CreateNumber((double)44);
cJSON_AddItemToArray(_n0, _n45);
cJSON *_n46 = cJSON_CreateNumber((double)45);
cJSON_AddItemToArray(_n0, _n46);
cJSON *_n47 = cJSON_CreateNumber((double)46);
cJSON_AddItemToArray(_n0, _n47);
cJSON *_n48 = cJSON_CreateNumber((double)47);
cJSON_AddItemToArray(_n0, _n48);
cJSON *_n49 = cJSON_CreateNumber((double)48);
cJSON_AddItemToArray(_n0, _n49);
cJSON *_n50 = cJSON_CreateNumber((double)49);
cJSON_AddItemToArray(_n0, _n50);
cJSON *_n51 = cJSON_CreateNumber((double)50);
cJSON_AddItemToArray(_n0, _n51);
cJSON *_n52 = cJSON_CreateNumber((double)51);
cJSON_AddItemToArray(_n0, _n52);
cJSON *_n53 = cJSON_CreateNumber((double)52);
cJSON_AddItemToArray(_n0, _n53);
cJSON *_n54 = cJSON_CreateNumber((double)53);
cJSON_AddItemToArray(_n0, _n54);
cJSON *_n55 = cJSON_CreateNumber((double)54);
cJSON_AddItemToArray(_n0, _n55);
cJSON *_n56 = cJSON_CreateNumber((double)55);
cJSON_AddItemToArray(_n0, _n56);
cJSON *_n57 = cJSON_CreateNumber((double)56);
cJSON_AddItemToArray(_n0, _n57);
cJSON *_n58 = cJSON_CreateNumber((double)57);
cJSON_AddItemToArray(_n0, _n58);
cJSON *_n59 = cJSON_CreateNumber((double)58);
cJSON_AddItemToArray(_n0, _n59);
cJSON *_n60 = cJSON_CreateNumber((double)59);
cJSON_AddItemToArray(_n0, _n60);
cJSON *_n61 = cJSON_CreateNumber((double)60);
cJSON_AddItemToArray(_n0, _n61);
cJSON *_n62 = cJSON_CreateNumber((double)61);
cJSON_AddItemToArray(_n0, _n62);
cJSON *_n63 = cJSON_CreateNumber((double)62);
cJSON_AddItemToArray(_n0, _n63);
cJSON *_n64 = cJSON_CreateNumber((double)63);
cJSON_AddItemToArray(_n0, _n64);
cJSON *_n65 = cJSON_CreateNumber((double)64);
cJSON_AddItemToArray(_n0, _n65);
cJSON *_n66 = cJSON_CreateNumber((double)65);
cJSON_AddItemToArray(_n0, _n66);
cJSON *_n67 = cJSON_CreateNumber((double)66);
cJSON_AddItemToArray(_n0, _n67);
cJSON *_n68 = cJSON_CreateNumber((double)67);
cJSON_AddItemToArray(_n0, _n68);
cJSON *_n69 = cJSON_CreateNumber((double)68);
cJSON_AddItemToArray(_n0, _n69);
cJSON *_n70 = cJSON_CreateNumber((double)69);
cJSON_AddItemToArray(_n0, _n70);
cJSON *_n71 = cJSON_CreateNumber((double)70);
cJSON_AddItemToArray(_n0, _n71);
cJSON *_n72 = cJSON_CreateNumber((double)71);
cJSON_AddItemToArray(_n0, _n72);
cJSON *_n73 = cJSON_CreateNumber((double)72);
cJSON_AddItemToArray(_n0, _n73);
cJSON *_n74 = cJSON_CreateNumber((double)73);
cJSON_AddItemToArray(_n0, _n74);
cJSON *_n75 = cJSON_CreateNumber((double)74);
cJSON_AddItemToArray(_n0, _n75);
cJSON *_n76 = cJSON_CreateNumber((double)75);
cJSON_AddItemToArray(_n0, _n76);
cJSON *_n77 = cJSON_CreateNumber((double)76);
cJSON_AddItemToArray(_n0, _n77);
cJSON *_n78 = cJSON_CreateNumber((double)77);
cJSON_AddItemToArray(_n0, _n78);
cJSON *_n79 = cJSON_CreateNumber((double)78);
cJSON_AddItemToArray(_n0, _n79);
cJSON *_n80 = cJSON_CreateNumber((double)79);
cJSON_AddItemToArray(_n0, _n80);
cJSON *_n81 = cJSON_CreateNumber((double)80);
cJSON_AddItemToArray(_n0, _n81);
cJSON *_n82 = cJSON_CreateNumber((double)81);
cJSON_AddItemToArray(_n0, _n82);
cJSON *_n83 = cJSON_CreateNumber((double)82);
cJSON_AddItemToArray(_n0, _n83);
cJSON *_n84 = cJSON_CreateNumber((double)83);
cJSON_AddItemToArray(_n0, _n84);
cJSON *_n85 = cJSON_CreateNumber((double)84);
cJSON_AddItemToArray(_n0, _n85);
cJSON *_n86 = cJSON_CreateNumber((double)85);
cJSON_AddItemToArray(_n0, _n86);
cJSON *_n87 = cJSON_CreateNumber((double)86);
cJSON_AddItemToArray(_n0, _n87);
cJSON *_n88 = cJSON_CreateNumber((double)87);
cJSON_AddItemToArray(_n0, _n88);
cJSON *_n89 = cJSON_CreateNumber((double)88);
cJSON_AddItemToArray(_n0, _n89);
cJSON *_n90 = cJSON_CreateNumber((double)89);
cJSON_AddItemToArray(_n0, _n90);
cJSON *_n91 = cJSON_CreateNumber((double)90);
cJSON_AddItemToArray(_n0, _n91);
cJSON *_n92 = cJSON_CreateNumber((double)91);
cJSON_AddItemToArray(_n0, _n92);
cJSON *_n93 = cJSON_CreateNumber((double)92);
cJSON_AddItemToArray(_n0, _n93);
cJSON *_n94 = cJSON_CreateNumber((double)93);
cJSON_AddItemToArray(_n0, _n94);
cJSON *_n95 = cJSON_CreateNumber((double)94);
cJSON_AddItemToArray(_n0, _n95);
cJSON *_n96 = cJSON_CreateNumber((double)95);
cJSON_AddItemToArray(_n0, _n96);
cJSON *_n97 = cJSON_CreateNumber((double)96);
cJSON_AddItemToArray(_n0, _n97);
cJSON *_n98 = cJSON_CreateNumber((double)97);
cJSON_AddItemToArray(_n0, _n98);
cJSON *_n99 = cJSON_CreateNumber((double)98);
cJSON_AddItemToArray(_n0, _n99);
cJSON *_n100 = cJSON_CreateNumber((double)99);
cJSON_AddItemToArray(_n0, _n100);
cJSON *_n101 = cJSON_CreateNumber((double)100);
cJSON_AddItemToArray(_n0, _n101);
cJSON *_n102 = cJSON_CreateNumber((double)101);
cJSON_AddItemToArray(_n0, _n102);
cJSON *_n103 = cJSON_CreateNumber((double)102);
cJSON_AddItemToArray(_n0, _n103);
cJSON *_n104 = cJSON_CreateNumber((double)103);
cJSON_AddItemToArray(_n0, _n104);
cJSON *_n105 = cJSON_CreateNumber((double)104);
cJSON_AddItemToArray(_n0, _n105);
cJSON *_n106 = cJSON_CreateNumber((double)105);
cJSON_AddItemToArray(_n0, _n106);
cJSON *_n107 = cJSON_CreateNumber((double)106);
cJSON_AddItemToArray(_n0, _n107);
cJSON *_n108 = cJSON_CreateNumber((double)107);
cJSON_AddItemToArray(_n0, _n108);
cJSON *_n109 = cJSON_CreateNumber((double)108);
cJSON_AddItemToArray(_n0, _n109);
cJSON *_n110 = cJSON_CreateNumber((double)109);
cJSON_AddItemToArray(_n0, _n110);
cJSON *_n111 = cJSON_CreateNumber((double)110);
cJSON_AddItemToArray(_n0, _n111);
cJSON *_n112 = cJSON_CreateNumber((double)111);
cJSON_AddItemToArray(_n0, _n112);
cJSON *_n113 = cJSON_CreateNumber((double)112);
cJSON_AddItemToArray(_n0, _n113);
cJSON *_n114 = cJSON_CreateNumber((double)113);
cJSON_AddItemToArray(_n0, _n114);
cJSON *_n115 = cJSON_CreateNumber((double)114);
cJSON_AddItemToArray(_n0, _n115);
cJSON *_n116 = cJSON_CreateNumber((double)115);
cJSON_AddItemToArray(_n0, _n116);
cJSON *_n117 = cJSON_CreateNumber((double)116);
cJSON_AddItemToArray(_n0, _n117);
cJSON *_n118 = cJSON_CreateNumber((double)117);
cJSON_AddItemToArray(_n0, _n118);
cJSON *_n119 = cJSON_CreateNumber((double)118);
cJSON_AddItemToArray(_n0, _n119);
cJSON *_n120 = cJSON_CreateNumber((double)119);
cJSON_AddItemToArray(_n0, _n120);
cJSON *my_data = _n0;
    (void)my_data;
    return 0;
}
