typedef enum int {_VVAL_BOOL, _VVAL_INT, _VVAL_REAL, _VVAL_STR} _VTag;
typedef struct {
    _VTag tag;
    longint i;
    real r;
    string s;
} _VVal;
typedef struct {
    string k;
    _VVal v;
} _VKV;
module main;
initial begin
static _VVal my_data[] = '{
    _VVal'{tag: _VVAL_INT, i: 0, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 1, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 2, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 3, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 4, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 5, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 6, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 7, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 8, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 9, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 10, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 11, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 12, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 13, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 14, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 15, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 16, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 17, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 18, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 19, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 20, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 21, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 22, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 23, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 24, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 25, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 26, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 27, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 28, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 29, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 30, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 31, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 32, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 33, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 34, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 35, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 36, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 37, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 38, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 39, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 40, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 41, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 42, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 43, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 44, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 45, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 46, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 47, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 48, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 49, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 50, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 51, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 52, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 53, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 54, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 55, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 56, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 57, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 58, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 59, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 60, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 61, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 62, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 63, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 64, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 65, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 66, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 67, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 68, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 69, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 70, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 71, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 72, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 73, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 74, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 75, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 76, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 77, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 78, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 79, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 80, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 81, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 82, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 83, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 84, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 85, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 86, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 87, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 88, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 89, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 90, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 91, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 92, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 93, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 94, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 95, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 96, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 97, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 98, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 99, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 100, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 101, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 102, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 103, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 104, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 105, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 106, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 107, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 108, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 109, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 110, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 111, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 112, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 113, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 114, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 115, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 116, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 117, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 118, r: 0.0, s: ""},
    _VVal'{tag: _VVAL_INT, i: 119, r: 0.0, s: ""}
};
end
endmodule
