class _ThrottlerType:
    def check(self, user_id: object, ts: object) -> object: ...
throttler = _ThrottlerType()
def emit(_arg: object) -> object: ...
emit(throttler.check(user_id="user_1", ts=1000.0))
emit(throttler.check(user_id="user_2", ts=2000.5))
