(define throttler (lambda args 0))
(define throttler.check (lambda args 0))
(define emit (lambda args (if #f #f)))
(emit (throttler.check user_id "user_1" ts 1000.0))
(emit (throttler.check user_id "user_2" ts 2000.5))
