val my_data = mapOf<String, Int>(
    "assert" to 1,
    "else" to 1,
    "error" to 1,
    "false" to 1,
    "for" to 1,
    "function" to 1,
    "if" to 1,
    "import" to 1,
    "importbin" to 1,
    "importstr" to 1,
    "in" to 1,
    "local" to 1,
    "null" to 1,
    "self" to 1,
    "super" to 1,
    "tailstrict" to 1,
    "then" to 1,
    "true" to 1,
    "ordinary" to 1,
)
