var my_data: Record<string, number> = {
  "assert": 1,
  "else": 1,
  "error": 1,
  "false": 1,
  "for": 1,
  "function": 1,
  "if": 1,
  "import": 1,
  "importbin": 1,
  "importstr": 1,
  "in": 1,
  "local": 1,
  "null": 1,
  "self": 1,
  "super": 1,
  "tailstrict": 1,
  "then": 1,
  "true": 1,
  "ordinary": 1,
};
my_data = {
  "assert": 1,
  "else": 1,
  "error": 1,
  "false": 1,
  "for": 1,
  "function": 1,
  "if": 1,
  "import": 1,
  "importbin": 1,
  "importstr": 1,
  "in": 1,
  "local": 1,
  "null": 1,
  "self": 1,
  "super": 1,
  "tailstrict": 1,
  "then": 1,
  "true": 1,
  "ordinary": 1,
};
export {};
