(create-ns 'my_app.http_client)
(intern 'my_app.http_client 'fetch (fn [& _args] nil))
(my_app.http_client/fetch :payload "hello")
(my_app.http_client/fetch :payload 42)
(my_app.http_client/fetch :payload true)
