(define my_app (lambda args (if #f #f)))
(define my_app.http_client (lambda args (if #f #f)))
(define my_app.http_client.fetch (lambda args (if #f #f)))
(my_app.http_client.fetch payload "hello")
(my_app.http_client.fetch payload 42)
(my_app.http_client.fetch payload #t)
