(defn obj [& args] nil)
(defn obj.api [& args] nil)
(defn obj.api.client [& args] nil)
(defn obj.api.client.post [& args] nil)
(obj.api.client.post :data "hello")
(obj.api.client.post :data 42)
(obj.api.client.post :data true)
