(define app (lambda args (if #f #f)))
(define app.client (lambda args (if #f #f)))
(define app.client.fetch (lambda args (if #f #f)))
(app.client.fetch payload "hello")
(app.client.fetch payload 42)
(app.client.fetch payload #t)
