from __future__ import annotations
def process(*_args: object, **_kwargs: object) -> object: ...
def emit(*_args: object, **_kwargs: object) -> object: ...
emit(process(value="hello"), True)
emit(process(value=42), False)
