(defun app (&rest args) (declare (ignore args)) nil)
(defun app.client (&rest args) (declare (ignore args)) nil)
(defun app.client.fetch (&rest args) (declare (ignore args)) nil)
(app.client.fetch :value "hello")
(app.client.fetch :value "world")
