import datetime
def check(*_args: object, **_kwargs: object) -> object: ...
check(ts=datetime.datetime(year=2024, month=1, day=15, hour=10, minute=30, second=0, tzinfo=datetime.UTC), d=datetime.date(year=2024, month=6, day=1))
