---
name: Lint C#

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Initialize .NET runtime
        if: steps.changes.outputs.relevant == 'true'
        run: |
          mkdir -p /tmp/.dotnet/shm
          dotnet --info
      - name: Install uv
        if: steps.changes.outputs.relevant == 'true'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/pyproject.toml'
      - name: Check C# syntax
        if: steps.changes.outputs.relevant == 'true'
        run: >-
          find tests/integration/cases -name "*.cs" -print0 |
          xargs -0 uv run python check_csharp_golden_syntax.py
