---
name: Lint D

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.d
      - name: Install DMD
        if: steps.lint-lang.outputs.found == 'true'
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: dmd-latest
      - name: Check D syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            dmd -o- -c "$f" || exit 1
          done < /tmp/files-to-lint
