---
name: Lint Jsonnet

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-jsonnet:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.jsonnet
          lint_command: |-
            sudo apt-get update -qq
            sudo apt-get install -y -qq jsonnet
            while IFS= read -r -d '' f; do
              jsonnet "$f" > /dev/null || exit 1
            done < /tmp/files-to-lint
