---
name: Lint YAML

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: |
            tests/integration/cases/**/*.yaml
            !tests/integration/cases/**/input.yaml
          exclude_patterns: input.yaml
      - name: Install uv
        if: steps.lint-lang.outputs.found == 'true'
        uses: astral-sh/setup-uv@v7
      - name: Check YAML syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: |-
          xargs -0 uvx yamllint --strict -d '{extends: default, rules: {document-start: disable, line-length: disable}}' -- < /tmp/files-to-lint
