---
name: Lint Swift

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-swift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.swift
      - name: Install Swift
        if: steps.lint-lang.outputs.found == 'true'
        uses: SwiftyLab/setup-swift@v1
        with:
          cache-snapshot: true
      - name: Check Swift syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            tmpdir=$(mktemp -d)
            cp "$f" "$tmpdir/check.swift"
            swiftc -typecheck "$tmpdir/check.swift" || exit 1
          done < /tmp/files-to-lint
