---
name: Lint Swift

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-swift:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.swift
          find_command: find tests/integration/cases -name "*.swift" -print0
      - name: Install Swift
        if: steps.find-files.outputs.found == 'true'
        uses: SwiftyLab/setup-swift@v1
        with:
          cache-snapshot: true
      - name: Check Swift syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            tmpdir=$(mktemp -d)
            cp "$f" "$tmpdir/check.swift"
            swiftc -typecheck "$tmpdir/check.swift" || exit 1
          done < /tmp/files-to-lint
