---
name: Lint PHP

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.php
          find_command: find tests/integration/cases -name "*.php" -print0
      - name: Check PHP syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 php -l < /tmp/files-to-lint
