---
name: Lint Go

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.go
          lint_command: |-
            xargs -0 gofmt -e < /tmp/files-to-lint
            xargs -0 -n1 go vet < /tmp/files-to-lint
