---
name: Lint TypeScript

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.ts
          exclude_dirs: |
            tests/integration/cases/comment_scalar
            tests/integration/cases/comment_scalar_document_markers
            tests/integration/cases/comment_scalar_only_comments
      - name: Install TypeScript
        if: steps.find-files.outputs.found == 'true'
        run: npm install -g typescript
      - name: Check TypeScript syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            tsc --noEmit --noResolve --skipLibCheck --lib es2015 "$f" || exit 1
          done < /tmp/files-to-lint
