---
name: Lint Racket

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-racket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.rkt
      - name: Install Racket
        if: steps.find-files.outputs.found == 'true'
        run: sudo apt-get install -y racket
      - name: Check Racket syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 raco make < /tmp/files-to-lint
