---
name: Lint PowerShell

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Check PowerShell syntax
        if: steps.changes.outputs.relevant == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.ps1" -print0 | \
            while IFS= read -r -d '' f; do
              pwsh -NoProfile -NonInteractive -Command \
                "\$null = [scriptblock]::Create((Get-Content -Raw '$f'))" || exit 1
            done
