---
name: Lint Groovy

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install Groovy
        if: steps.changes.outputs.relevant == 'true'
        uses: wtfjoke/setup-groovy@v3
        with:
          groovy-version: 4.x
      - name: Check Groovy syntax
        if: steps.changes.outputs.relevant == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.groovy" -print0 | \
            while IFS= read -r -d '' f; do
              tmpdir=$(mktemp -d)
              groovyc -d "$tmpdir" "$(realpath "$f")" || exit 1
            done
