---
name: Lint Mojo

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-mojo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install pixi
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        uses: fabasoad/setup-mojo-action@v3
      - name: Install Mojo
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          pixi global install --channel conda-forge --channel https://conda.modular.com/max mojo
      - name: Check Mojo syntax
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.mojo" -print0 | \
            while IFS= read -r -d '' f; do
              if ! mojo run "$f"; then
                exit 1
              fi
            done
