---
name: Lint Java

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.java
          lint_command: |-
            tmpdir=$(mktemp -d)
            while IFS= read -r -d '' f; do
              javac -d "$tmpdir" "$f" || exit 1
            done < /tmp/files-to-lint
