---
name: Lint Go

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.go
          find_command: find tests/integration/cases -name "*.go" -print0
      - name: Check Go syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 gofmt -e < /tmp/files-to-lint
      - name: Check Go compilation
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 -n1 go vet < /tmp/files-to-lint
