---
name: Lint Clojure

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-clojure:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.clj
      - name: Install clj-kondo
        if: steps.lint-lang.outputs.found == 'true'
        uses: DeLaGuardo/setup-clojure@13
        with:
          clj-kondo: latest
      - name: Check Clojure syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: xargs -0 clj-kondo --lint < /tmp/files-to-lint
