---
name: Lint Kotlin

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.kts
          find_command: find tests/integration/cases -name "*.kts" -print0
      - name: Install Kotlin
        if: steps.find-files.outputs.found == 'true'
        uses: fwilhe2/setup-kotlin@v1
      - name: Check Kotlin syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          xargs -0 -P "$(nproc)" -n 1 kotlinc -script < /tmp/files-to-lint
