---
name: Lint Dhall

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-dhall:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.dhall
          lint_command: |-
            curl -fsSL https://github.com/dhall-lang/dhall-haskell/releases/download/1.42.2/dhall-1.42.2-x86_64-linux.tar.bz2 \
              | tar -xj
            export PATH="$PWD/bin:$PATH"
            while IFS= read -r -d '' f; do
              dhall < "$f" > /dev/null || exit 1
            done < /tmp/files-to-lint
