---
name: Lint Nim

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-nim:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.nim
      - name: Install Nim
        if: steps.lint-lang.outputs.found == 'true'
        uses: jiro4989/setup-nim-action@v2
      - name: Check Nim syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            tmpdir=$(mktemp -d)
            nim check --hints:off --nimcache:"$tmpdir" "$f" || exit 1
          done < /tmp/files-to-lint
