---
name: Lint Mojo

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-mojo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install pixi
        uses: fabasoad/setup-mojo-action@v3
      - name: Install Mojo
        run: |-
          pixi global install --channel conda-forge --channel https://conda.modular.com/max mojo
      - name: Check Mojo syntax
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.mojo" -print0 | \
            while IFS= read -r -d '' f; do
              mojo run "$f" || exit 1
            done
