---
name: Lint Nim

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-nim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install Nim
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        uses: jiro4989/setup-nim-action@v2
      - name: Check Nim syntax
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.nim" -print0 | \
            while IFS= read -r -d '' f; do
              tmpdir=$(mktemp -d)
              nim check --hints:off --nimcache:"$tmpdir" "$f" || exit 1
            done
