---
name: Lint Groovy

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.groovy
          find_command: find tests/integration/cases -name "*.groovy" -print0
      - name: Install Groovy
        if: steps.find-files.outputs.found == 'true'
        uses: wtfjoke/setup-groovy@v3
        with:
          groovy-version: 4.x
      - name: Check Groovy syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            tmpdir=$(mktemp -d)
            groovyc -d "$tmpdir" "$(realpath "$f")" || exit 1
          done < /tmp/files-to-lint
