---
name: Lint TypeScript

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.ts
          lint_command: |-
            npm install -g typescript
            while IFS= read -r -d '' f; do
              tsc --noEmit --noResolve --skipLibCheck --lib es2015 "$f" || exit 1
            done < /tmp/files-to-lint
