---
name: Lint Bash

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Check Bash syntax
        run: find tests/integration/cases -name "*.sh" -exec bash -n {} +
