---
name: Lint TypeScript

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install TypeScript
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: npm install -g typescript
      - name: Check TypeScript syntax
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.ts" -print0 | \
            while IFS= read -r -d '' f; do
              tsc --noEmit --noResolve --skipLibCheck --lib es2015 "$f" || exit 1
            done
