---
name: Lint Perl

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-perl:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.pl
          find_command: find tests/integration/cases -name "*.pl" -print0
      - name: Install Perl dependencies
        if: steps.find-files.outputs.found == 'true'
        run: |-
          sudo apt-get update
          sudo apt-get install -y cpanminus
          sudo cpanm --notest DateTime
      - name: Check Perl syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            perl -c "$f" || exit 1
          done < /tmp/files-to-lint
