---
name: Lint Scheme

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-scheme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.scm
      - name: Install Guile
        if: steps.find-files.outputs.found == 'true'
        run: sudo apt-get install -y guile-3.0
      - name: Check Scheme syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 -I{} guile --no-auto-compile -s {} < /tmp/files-to-lint
