---
name: Lint Perl

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install Perl dependencies
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: cpanm --notest DateTime
      - name: Check Perl syntax
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.pl" -print0 | \
            while IFS= read -r -d '' f; do
              perl -c "$f" || exit 1
            done
