---
name: Lint Common Lisp

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-common-lisp:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.lisp
          find_command: find tests/integration/cases -name "*.lisp" -print0
      - name: Install SBCL
        if: steps.find-files.outputs.found == 'true'
        run: sudo apt-get install -y sbcl
      - name: Check Common Lisp syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 -I{} sbcl --script {} < /tmp/files-to-lint
