---
name: Lint Java

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.java
          find_command: find tests/integration/cases -name "*.java" -print0
      - name: Check Java syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          tmpdir=$(mktemp -d)
          while IFS= read -r -d '' f; do
            javac -d "$tmpdir" "$f" || exit 1
          done < /tmp/files-to-lint
