---
name: Lint Gleam

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-gleam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.gleam
      - name: Install Gleam
        if: steps.find-files.outputs.found == 'true'
        uses: erlef/setup-beam@v1
        with:
          gleam-version: latest
          otp-version: 27
      - name: Check Gleam syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 gleam format < /tmp/files-to-lint
