---
name: Lint OCaml

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-ocaml:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.ml
          find_command: find tests/integration/cases -name "*.ml" -print0
      - name: Install OCaml
        if: steps.find-files.outputs.found == 'true'
        run: sudo apt-get install -y ocaml
      - name: Check OCaml syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          tmpdir=$(mktemp -d)
          while IFS= read -r -d '' f; do
            ocamlopt -c -o "$tmpdir/check.o" "$f" || exit 1
          done < /tmp/files-to-lint
