---
name: Lint Fortran

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-fortran:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install gfortran
        if: steps.changes.outputs.relevant == 'true'
        run: sudo apt-get install -y gfortran
      - name: Check Fortran syntax
        if: steps.changes.outputs.relevant == 'true'
        run: find tests/integration/cases -name "*.f90" -exec gfortran -std=f2008
          -ffree-line-length-none -fsyntax-only {} +
