---
name: Lint Zig

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install Zig
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - name: Check Zig
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.zig" -print0 | \
            while IFS= read -r -d '' f; do
              zig build-obj -fno-emit-bin "$f" || exit 1
            done
