---
name: Lint JSON5

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-json5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.json5
      - name: Install json5
        if: steps.find-files.outputs.found == 'true'
        run: npm install -g json5
      - name: Check JSON5 syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            json5 "$f" > /dev/null || exit 1
          done < /tmp/files-to-lint
