---
name: Lint C++

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.cpp
          find_command: find tests/integration/cases -name "*.cpp" -print0
      - name: Check C++ syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 clang++ -fsyntax-only -std=c++20 < /tmp/files-to-lint
