---
name: Lint Crystal

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-crystal:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.cr
      - name: Install Crystal
        if: steps.lint-lang.outputs.found == 'true'
        uses: crystal-lang/install-crystal@v1
      - name: Check Crystal syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            crystal build --no-codegen "$f" || exit 1
          done < /tmp/files-to-lint
