---
name: Lint Zig

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-zig:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.zig
          find_command: find tests/integration/cases -name "*.zig" -print0
      - name: Install Zig
        if: steps.find-files.outputs.found == 'true'
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0
      - name: Check Zig
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            zig build-obj -fno-emit-bin "$f" || exit 1
          done < /tmp/files-to-lint
