---
name: Lint Odin

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-odin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.odin
      - name: Install Odin
        if: steps.find-files.outputs.found == 'true'
        run: |-
          sudo apt-get update -qq
          sudo apt-get install -y -qq llvm-14 clang-14
          git clone --depth=1 https://github.com/odin-lang/Odin /tmp/odin
          cd /tmp/odin && make release
          echo "/tmp/odin" >> "$GITHUB_PATH"
      - name: Check Odin
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            odin check "$f" -file || exit 1
          done < /tmp/files-to-lint
