---
name: Lint Jsonnet

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-jsonnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.jsonnet
      - name: Install jsonnet
        if: steps.find-files.outputs.found == 'true'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq jsonnet
      - name: Check Jsonnet syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            jsonnet "$f" > /dev/null || exit 1
          done < /tmp/files-to-lint
