---
name: Lint Lua

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.lua
          find_command: find tests/integration/cases -name "*.lua" -print0
      - name: Install Lua
        if: steps.find-files.outputs.found == 'true'
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: '5.4'
      - name: Check Lua syntax
        if: steps.find-files.outputs.found == 'true'
        run: xargs -0 luac -p < /tmp/files-to-lint
