---
name: Lint Racket

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-racket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install Racket
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: sudo apt-get install -y racket
      - name: Check Racket syntax
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: >-
          find tests/integration/cases -name "*.rkt" -print0 |
          xargs -0 raco make
