---
name: Lint COBOL

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-cobol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install GnuCOBOL
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: sudo apt-get install -y gnucobol
      - name: Check COBOL syntax
        if: github.event_name != 'pull_request' || steps.changes.outputs.relevant
          == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.cob" -print0 | \
            while IFS= read -r -d '' f; do
              cobc -free -fsyntax-only "$f" || exit 1
            done
