---
name: Lint Scala

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-scala:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/find-lint-files
        id: find-files
        with:
          lang_patterns: tests/integration/cases/**/*.scala
          find_command: find tests/integration/cases -name "*.scala" -print0
      - name: Install Scala
        if: steps.find-files.outputs.found == 'true'
        uses: coursier/setup-action@v3
        with:
          apps: scalac
      - name: Check Scala syntax
        if: steps.find-files.outputs.found == 'true'
        run: |-
          while IFS= read -r -d '' f; do
            tmpdir=$(mktemp -d)
            scalac -d "$tmpdir" "$f" || exit 1
          done < /tmp/files-to-lint
