---
name: Lint Ada

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-ada:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/lint-lang
        id: lint-lang
        with:
          lang_patterns: tests/integration/cases/**/*.adb
          extra_config_patterns: check_ada_golden_syntax.py
      - name: Install GNAT
        if: steps.lint-lang.outputs.found == 'true'
        run: sudo apt-get install -y gnat
      - name: Install uv
        if: steps.lint-lang.outputs.found == 'true'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/pyproject.toml'
      - name: Check Ada syntax
        if: steps.lint-lang.outputs.found == 'true'
        run: xargs -0 uv run --no-project python check_ada_golden_syntax.py < /tmp/files-to-lint
