---
name: Lint Scala

on:
  workflow_call: {}

permissions: {}

jobs:
  lint-scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |-
            relevant:
              - 'tests/integration/cases/**'
              - '**/*.yml'
              - '**/*.toml'
      - name: Install Scala
        if: steps.changes.outputs.relevant == 'true'
        uses: coursier/setup-action@v3
        with:
          apps: scalac
      - name: Check Scala syntax
        if: steps.changes.outputs.relevant == 'true'
        run: |-
          set -o pipefail
          find tests/integration/cases -name "*.scala" -print0 | \
            while IFS= read -r -d '' f; do
              tmpdir=$(mktemp -d)
              scalac -d "$tmpdir" "$f" || exit 1
            done
